name: flutter2048
description: 2048 game made with Flutter.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
